require('conf.impatient')
require("conf.cyberdream")
require("conf.autocmd")
require("conf.nvimtree")
require("conf.treesitter")
require("conf.cmp")
require("conf.go")
require("conf.telescope")
require("conf.toggleterm")
require("conf.colorizer")
require("conf.notify")
require("conf.todocomment")
require("conf.lspfuzzy")
require("conf.dap")
require("conf.lsp_signature")
require("conf.lazygit")
require("conf.bufferline")
require("conf.lualine")
require("conf.fidget")

-- 确保这些配置按照以下顺序加载
require("conf.mason")
require("conf.lspconfig") -- 这应该包含您的 LSP 服务器设置
