require('conf.onedark')
require('conf.nvimtree')
require('conf.treesitter')
require('conf.cmp')
-- require('conf.cmp_cus')
require('conf.go')
-- require('conf.bufferline')
require('conf.autosave')
require('conf.telescope')
-- require('conf.lsp')
require('conf.toggleterm')
require('conf.colorizer')
require('conf.notify')
require('conf.todocomment')
require('conf.lspfuzzy')
-- require('conf.lspinstall')
-- require('conf.lspconf')
require('conf.dap')
require('conf.lsp_signature')
require('conf.git')
require('conf.mason')
require('conf.mason.init')
